name: Build and publish site
on:
  workflow_dispatch:
  push:
    branches:
      - docs

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'docs'
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Build
      run: dotnet build src
    - name: Publish
      run: |
        #!/bin/bash
        
        cd _site
        
        $remote_repo="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        $remote_branch="gh-bages"
        
        git init
        git checkout -b scratch
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        
        git commit -m "GitHub Action - Automated build"
        git push --force $remote_repo scratch:$remote_branch
      
